/*
 * BuildingConfigurationGui.java
 *
 * Created on 26 de febrero de 2009, 12:20
 */

package sim.app.ubik.building;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;

/**
 *
  * @author Juan A. Botía, Pablo Campillo, Francisco Campuzano, and Emilio Serrano
 */
public class BuildingConfigurationGui extends javax.swing.JDialog {

protected ArrayList configuration;
    /** Creates new form BuildingConfigurationGui 
     Se le pasa un arrayList inicializado que se devuelve con los parametros del edificio*/
    public BuildingConfigurationGui(ArrayList configuration) {
        this.configuration= configuration;
        int min = 0;
        int max = Integer.MAX_VALUE;
        int step = 1;
        this.setResizable(false);           
        initComponents();
        this.setModal( true );
          this.setLocationRelativeTo(null);
          
         f.setModel(new SpinnerNumberModel(3, min, max, step));
         fw.setModel(new SpinnerNumberModel(100, min, max, step));
         fh.setModel(new SpinnerNumberModel(100, min, max, step));
         hc.setModel(new SpinnerNumberModel(1, min, max, step));
         vc.setModel(new SpinnerNumberModel(3, min, max, step));
         cw.setModel(new SpinnerNumberModel(4, min, max, step));
         dw.setModel(new SpinnerNumberModel(2, min, max, step));
         ww.setModel(new SpinnerNumberModel(2, min, max, step));
         sw.setModel(new SpinnerNumberModel(2, min, max, step));
         sl.setModel(new SpinnerNumberModel(10, min, max, step));
         buttonsStairs.add(this.sinhcorridor);
         buttonsStairs.add(this.sinvcorridor);
         buttonsStairs.add(this.sinvandhcorridor);
         this.sinvandhcorridor.setSelected(true);
         calculateRooms();
    }
    
    private void calculateRooms(){
      int h = (new Integer (hc.getValue().toString())).intValue();
      int v = (new Integer (vc.getValue().toString())).intValue();
      Integer rooms = new Integer((h+1)*(v+1));
      r.setText(rooms.toString());
    }

    /**
     * Comprueba la consistencia de los valores introducidos. False si son inconsistentes, por ejemplo la anchura de la escalera es mayor que la anchura del pasillo.
     * @return
     */
    private boolean checkParameters() {
       int corridorw = (new Integer (cw.getValue().toString())).intValue();
       int stairsw= (new Integer (sw.getValue().toString())).intValue();
       if(corridorw < stairsw){
           showError("The corridor width must be bigger or equal than the staris width");
           return false;
       }
       return true;
    }

    
    private void showError(String message){
        JOptionPane.showMessageDialog(this,message,"Error", JOptionPane.ERROR_MESSAGE);

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsStairs = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        f = new javax.swing.JSpinner();
        fw = new javax.swing.JSpinner();
        fh = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vc = new javax.swing.JSpinner();
        hc = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        r = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cw = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        dw = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        ww = new javax.swing.JSpinner();
        ok = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        sw = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sinvcorridor = new javax.swing.JRadioButton();
        sinhcorridor = new javax.swing.JRadioButton();
        sinvandhcorridor = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        sl = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ubik");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sim/app/ubik/resources/logo.png"))); // NOI18N
        jLabel1.setName("logo"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Building configuration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 102, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        f.setName("f"); // NOI18N

        fw.setName("fw"); // NOI18N

        fh.setName("fh"); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Floors");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Floor width");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Floor height");
        jLabel4.setName("jLabel4"); // NOI18N

        vc.setName("vc"); // NOI18N
        vc.addChangeListener(new javax.swing.event.ChangeListener() {
            @Override
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vcStateChanged(evt);
            }
        });

        hc.setName("hc"); // NOI18N
        hc.addChangeListener(new javax.swing.event.ChangeListener() {
            @Override
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hcStateChanged(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Vertical corridors");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Horizontal corridors");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Rooms");
        jLabel8.setName("jLabel8"); // NOI18N

        r.setEditable(false);
        r.setHorizontalAlignment(SwingConstants.RIGHT);
        r.setName("r"); // NOI18N

        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Corridors width");
        jLabel9.setName("jLabel9"); // NOI18N

        cw.setName("cw"); // NOI18N

        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("Doors width");
        jLabel10.setName("jLabel10"); // NOI18N

        dw.setName("dw"); // NOI18N

        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("Windows width");
        jLabel11.setName("jLabel11"); // NOI18N

        ww.setName("ww"); // NOI18N

        ok.setText("OK");
        ok.setName("ok"); // NOI18N
        ok.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Stairs width");
        jLabel12.setName("jLabel12"); // NOI18N

        sw.setName("sw"); // NOI18N

        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("Stairs in vertical corridors");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("Stairs in horizontal  corridors");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jLabel15.setText("Stairs in all corridors");
        jLabel15.setName("jLabel15"); // NOI18N

        sinvcorridor.setName("sinvcorridor"); // NOI18N

        sinhcorridor.setName("sinhcorridor"); // NOI18N

        sinvandhcorridor.setName("sinvandhcorridor"); // NOI18N

        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setText("Stairs long");
        jLabel16.setName("jLabel16"); // NOI18N

        sl.setName("sl"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sinvandhcorridor)
                            .addComponent(sinhcorridor)
                            .addComponent(sinvcorridor)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addGap(122, 122, 122)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dw, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ww, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cw, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hc, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fw, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vc, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sw, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ww, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel15)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sinvcorridor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sinhcorridor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sinvandhcorridor)))
                .addGap(18, 18, 18)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
    if(! checkParameters()) return;
    this.configuration.add((new Integer (f.getValue().toString())));
    this.configuration.add((new Integer (fw.getValue().toString())));
    this.configuration.add((new Integer (fh.getValue().toString())));
    this.configuration.add((new Integer (vc.getValue().toString())));
    this.configuration.add((new Integer (hc.getValue().toString())));

    this.configuration.add((new Integer (cw.getValue().toString())));
    this.configuration.add((new Integer (dw.getValue().toString())));
    this.configuration.add((new Integer (ww.getValue().toString())));
       this.configuration.add((new Integer (sw.getValue().toString())));
            this.configuration.add((new Integer (sl.getValue().toString())));
    if(this.sinvandhcorridor.isSelected()) {
        this.configuration.add(new Boolean(true));
        this.configuration.add(new Boolean(true));
    }
    else{
        this.configuration.add(new Boolean(this.sinvcorridor.isSelected()));
        this.configuration.add(new Boolean(this.sinhcorridor.isSelected()));
    }
    
    this.dispose();
}//GEN-LAST:event_okActionPerformed

private void vcStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vcStateChanged
this.calculateRooms();
}//GEN-LAST:event_vcStateChanged

private void hcStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hcStateChanged
this.calculateRooms();// TODO add your handling code here:
}//GEN-LAST:event_hcStateChanged

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonsStairs;
    private javax.swing.JSpinner cw;
    private javax.swing.JSpinner dw;
    private javax.swing.JSpinner f;
    private javax.swing.JSpinner fh;
    private javax.swing.JSpinner fw;
    private javax.swing.JSpinner hc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok;
    private javax.swing.JTextField r;
    private javax.swing.JRadioButton sinhcorridor;
    private javax.swing.JRadioButton sinvandhcorridor;
    private javax.swing.JRadioButton sinvcorridor;
    private javax.swing.JSpinner sl;
    private javax.swing.JSpinner sw;
    private javax.swing.JSpinner vc;
    private javax.swing.JSpinner ww;
    // End of variables declaration//GEN-END:variables

}
